query GetRamaisForPage($page: ID!) {
  getRamaisForPage(page: $page) {
    id
    name
    sector
    number
  }
}

query GetLenghtRamais($maxPages: ID!) {
  getLenghtRamais(maxPages: $maxPages)
}

query SearchRamal($word: String!) {
  searchRamal(word: $word) {
    id
    name
    sector
    number
  }
}
