export const cardup = {
  date: [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
  salada: [
    "Salad1",
    "Salad2",
    "Salad3",
    "Salad4",
    "Salad5",
    "Salad6",
    "Salad7",
  ],
  arroz: ["Rice1", "Rice2", "Rice3", "Rice4", "Rice5", "Rice6", "Rice7"],
  feijao: [
    "Beans1",
    "Beans2",
    "Beans3",
    "Beans4",
    "Beans5",
    "Beans6",
    "Beans7",
  ],
  carboidrato: [
    "Pasta1",
    "Pasta2",
    "Pasta3",
    "Pasta4",
    "Pasta5",
    "Pasta6",
    "Pasta7",
  ],
  proteina: [
    "Chicken1",
    "Chicken2",
    "Chicken3",
    "Chicken4",
    "Chicken5",
    "Chicken6",
    "Chicken7",
  ],
  sopa: ["Soup1", "Soup2", "Soup3", "Soup4", "Soup5", "Soup6", "Soup7"],
  complemento: ["Side1", "Side2", "Side3", "Side4", "Side5", "Side6", "Side7"],
  sobremesa: [
    "Dessert1",
    "Dessert2",
    "Dessert3",
    "Dessert4",
    "Dessert5",
    "Dessert6",
    "Dessert7",
  ],
};
