query LoadAllEventsInMonth($month: String!, $yearSelect: Int!) {
  loadAllEventsInMonth(month: $month, yearSelect: $yearSelect) {
    id
    host {
      name
      ramalNumber
      userRegistration
      email
    }
    location {
      id
      name
      color
    }
    rules
    totalPeoples
    initialTime
    finalTime
    support {
      computer
      projector
      water
      coffee
      flipSharp
      equipamentSong
      helpers
    }
  }
}
