query LoadEventsInData($date: String!) {
  loadEventsInData(date: $date) {
    id
    host {
      name
      ramalNumber
      userRegistration
      email
    }
    location
    rules
    totalPeoples
    initialTime
    finalTime
    support {
      computer
      projector
      water
      coffee
      flipSharp
      equipamentSong
      helpers
    }
  }
}
