query ScheduleRoomLoad {
  scheduleRoomLoad {
    id
    userCreated {
      name
      ramalNumber
      userRegistration
      email
    }
    location
    rules
    totalPeoples
    initialTime
    finalTime
    support {
      computer
      projector
      water
      coffee
      flipSharp
      equipamentSong
      helpers
    }
  }
}
