query GetRooms {
  getRooms {
    id
    location
  }
}
query LoadScheduleRoom {
  loadScheduleRoom {
    id
    userCreated {
      name
      ramalNumber
      userRegistration
      email
    }
    location

    rules
    totalPeoples

    initialTime
    finalTime
    support {
      computer
      projector
      water
      coffee
      flipSharp
      equipamentSong
      helpers
    }
  }
}
