query GetRooms {
  getRooms {
    id
    location
  }
}
query GetScheduleRoom {
  getScheduleRoom {
    id
    user_created {
      name
      ramal_number
      user_registration
      email
    }
    location
    rules
    total_peoples
    initial_time
    final_time
    support {
      computer
      projector
      water
      coffee
      flipSharp
      equipamentSong
      helpers
    }
  }
}
