// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import("./components/Avatar.vue")["default"]
    BarUp: typeof import('./components/TabHeader/BarUp.vue')['default']
    Card: typeof import('./components/Carousel/CardForCarousel/Card.vue')['default']
    CardTitle: typeof import('./components/Carousel/CardForCarousel/CardTitle.vue')['default']
    Carousel: typeof import('./components/Carousel/Carousel.vue')['default']
    CarouselTitles: typeof import('./components/Carousel/CarouselForCardsTitles/CarouselTitles.vue')['default']
    Custom_Separator: typeof import('./components/Separator/Custom_Separator.vue')['default']
    CustomSeparator: typeof import('./components/Separator/CustomSeparator.vue')['default']
    DeleteButton: typeof import("./components/buttons/DeleteButton.vue")["default"]
    DropDown: typeof import("./components/buttons/DropDown.vue")["default"]
    FabButton: typeof import("./components/buttons/FabButton.vue")["default"]
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home/Home.vue')['default']
    Image: typeof import('./components/Image/Image.vue')['default']
    LoaderButton: typeof import("./components/buttons/LoaderButton.vue")["default"]
    MakdownEditor: typeof import("./components/MakdownEditor.vue")["default"]
    OptionLocales: typeof import("./components/OptionLocales.vue")["default"]
    PageLogin: typeof import('./components/login/PageLogin.vue')['default']
    Paralax: typeof import('./components/Paralax/Paralax.vue')['default']
    PaymentButton: typeof import("./components/buttons/PaymentButton.vue")["default"]
    Rh_Divulga: typeof import('./components/Rh_DIvulga/Rh_Divulga.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendButton: typeof import("./components/buttons/SendButton.vue")["default"]
    Systems: typeof import('./components/HomeSystems/Systems.vue')['default']
    ThemeButton: typeof import("./components/buttons/ThemeButton.vue")["default"]
    ToggleTheme: typeof import("./components/ToggleTheme.vue")["default"]
    TranslationComponent: typeof import("./components/TranslationComponent.vue")["default"]
  }
}
